2021-07-29 13:32:03,714 ERROR: Exception on /rater [GET] [in c:\users\penie\hcpd-system\venv\lib\site-packages\flask\app.py:1454
Traceback (most recent call last):
  File "c:\users\penie\hcpd-system\venv\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\penie\hcpd-system\venv\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\penie\hcpd-system\venv\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\penie\hcpd-system\venv\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "c:\users\penie\hcpd-system\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\penie\hcpd-system\app\routes.py", line 108, in rater
    return render_template('rater.html', form=form)
  File "c:\users\penie\hcpd-system\venv\lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(
  File "c:\users\penie\hcpd-system\venv\lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
  File "c:\users\penie\hcpd-system\venv\lib\site-packages\jinja2\environment.py", line 1304, in render
    self.environment.handle_exception()
  File "c:\users\penie\hcpd-system\venv\lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\penie\hcpd-system\app\templates\rater.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\penie\hcpd-system\app\templates\base.html", line 1, in top-level template code
    {% extends "bootstrap/base.html" %}
  File "c:\users\penie\hcpd-system\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "c:\users\penie\hcpd-system\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block 'doc'
    {%- block html %}
  File "c:\users\penie\hcpd-system\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block 'html'
    {% block body -%}
  File "c:\users\penie\hcpd-system\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in block 'body'
    {% block content -%}
  File "C:\Users\penie\hcpd-system\app\templates\base.html", line 51, in block 'content'
    {% block app_content %}{% endblock %}
  File "C:\Users\penie\hcpd-system\app\templates\rater.html", line 7, in block 'app_content'
    {{ wtf.quick_form(form) }}
  File "c:\users\penie\hcpd-system\venv\lib\site-packages\jinja2\environment.py", line 474, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'wtf' is undefined
2021-07-29 14:06:31,287 ERROR: Exception on /rater [POST] [in c:\users\penie\hcpd-system\venv\lib\site-packages\flask\app.py:1454
Traceback (most recent call last):
  File "c:\users\penie\hcpd-system\venv\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\penie\hcpd-system\venv\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\penie\hcpd-system\venv\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\penie\hcpd-system\venv\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "c:\users\penie\hcpd-system\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\penie\hcpd-system\app\routes.py", line 107, in rater
    return render_template('rater.html', ratings=ratings, form=form)
  File "c:\users\penie\hcpd-system\venv\lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(
  File "c:\users\penie\hcpd-system\venv\lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
  File "c:\users\penie\hcpd-system\venv\lib\site-packages\jinja2\environment.py", line 1304, in render
    self.environment.handle_exception()
  File "c:\users\penie\hcpd-system\venv\lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\penie\hcpd-system\app\templates\rater.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "C:\Users\penie\hcpd-system\app\templates\base.html", line 1, in top-level template code
    {% extends "bootstrap/base.html" %}
  File "c:\users\penie\hcpd-system\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "c:\users\penie\hcpd-system\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block 'doc'
    {%- block html %}
  File "c:\users\penie\hcpd-system\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block 'html'
    {% block body -%}
  File "c:\users\penie\hcpd-system\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in block 'body'
    {% block content -%}
  File "C:\Users\penie\hcpd-system\app\templates\base.html", line 51, in block 'content'
    {% block app_content %}{% endblock %}
  File "C:\Users\penie\hcpd-system\app\templates\rater.html", line 13, in block 'app_content'
    <p>{{ rating.rater.username }}</p> rated {{ user_rating.rating }}
  File "c:\users\penie\hcpd-system\venv\lib\site-packages\jinja2\environment.py", line 474, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'user_rating' is undefined
2021-08-03 16:02:11,345 ERROR: Exception on / [GET] [in c:\users\penie\hcpd-system\venv\lib\site-packages\flask\app.py:1454
Traceback (most recent call last):
  File "c:\users\penie\hcpd-system\venv\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\penie\hcpd-system\venv\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\penie\hcpd-system\venv\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\penie\hcpd-system\venv\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "c:\users\penie\hcpd-system\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\penie\hcpd-system\app\routes.py", line 22, in home_page
    return render_template('home.html', users=users)
  File "c:\users\penie\hcpd-system\venv\lib\site-packages\flask\templating.py", line 148, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "c:\users\penie\hcpd-system\venv\lib\site-packages\jinja2\environment.py", line 1068, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "c:\users\penie\hcpd-system\venv\lib\site-packages\jinja2\environment.py", line 997, in get_template
    return self._load_template(name, globals)
  File "c:\users\penie\hcpd-system\venv\lib\site-packages\jinja2\environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "c:\users\penie\hcpd-system\venv\lib\site-packages\jinja2\loaders.py", line 137, in load
    code = environment.compile(source, name, filename)
  File "c:\users\penie\hcpd-system\venv\lib\site-packages\jinja2\environment.py", line 757, in compile
    self.handle_exception(source=source_hint)
  File "c:\users\penie\hcpd-system\venv\lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\penie\hcpd-system\app\templates\home.html", line 21, in template
    {% if user.username == 'admin'}
jinja2.exceptions.TemplateSyntaxError: unexpected '}'
2021-08-03 17:06:07,990 ERROR: Exception on /rater [GET] [in c:\users\penie\hcpd-system\venv\lib\site-packages\flask\app.py:1454
Traceback (most recent call last):
  File "c:\users\penie\hcpd-system\venv\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\penie\hcpd-system\venv\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\penie\hcpd-system\venv\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\penie\hcpd-system\venv\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "c:\users\penie\hcpd-system\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\penie\hcpd-system\app\routes.py", line 122, in rater
    form.rating.data = current_user.rating
AttributeError: 'Usernames' object has no attribute 'rating'
